# -*- coding: utf-8 -*-
"""Лабораторная работа №1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkoaI1kzbrPw64QkDc3_PP2VbL0SgLjR
"""

print('Hello World')

a = 5
b = 2
c = a + b
print(c)

a = 7.5
b = int(input())
h = ((a ** 2 - (b / 2) ** 2)) ** (0.5)
S = (1 / 2) * b * h
print(S)

a, b, c = map(int, input().split())
x = (a ** 2 + b ** 2 - c * c * c) // 2
print(x)

#1.
a = 5
b = int(input())
print(a * b)

#2.
a = int(input())
b = int(input())
print((a + b) ** 2)

#3.
c = int(input())
a = 15
b = 10
print((a+b) // c)

#4.
a = int(input())
b = int(input())
res = a ** 2 + 2 * a * b + b ** 2
print(res)

#5.
a, b, c = map(int, input().split())
P = a + b + c
p = (a + b + c) // 2
S = (p * (p - a) * (p - b) * (p - c)) ** (0.5)
print(S, P)

#6.
a = int(input())
b = int(input())
print(((a ** 3 + 14) / 5) * b)

#7.
a = int(input())
n = int(input())
print(a ** 2 // n)

#8.1.
a = float(input())
b = float(input())
print(a // b)

#8.2.
a = int(input())
b = int(input())
print(a * b)

#8.3.
a = int(input())
b = int(input())
print(a % b)

#1.
n = int(input())
d = n // (24 * 3600)
n = n % (24 * 3600)
h = n // 3600
n = n % 3600
m = n // 60
s = n % 60
print(d, h, m, s)

#2.
n = int(input())
print(n + n ** 2 + n * n * n)