# -*- coding: utf-8 -*-
"""Лабораторная работа №3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qr0hmH5TCvjgdFo_DrPQmCmy-5jvmrPt
"""

#1.
n = int(input())
if n == 1:
    print('Январь')
elif n == 2:
    print('Февраль')
elif n == 3:
    print('Апрель')
elif n == 4:
    print('Март')
elif n == 5:
    print('Май')
elif n == 6:
    print('Июнь')
elif n == 7:
    print('Июль')
elif n == 8:
    print('Август')
elif n == 9:
    print('Сентябрь')
elif n == 10:
    print('Ноябрь')
elif n == 11:
    print('Октябрь')
elif n == 12:
    print('Декабрь')
elif n > 12 or n < 1:
    print('Такого месяца не существует!')

#2.
n = int(input())
if n % 2 == 0:
  print('Число чётное')
else:
  print('Число нечётное')

#3.
N = int(input())
if N > 40:
  print('stonks')
elif N == 40:
  print()
else:
  print('not stonks')

#4.
def is_year_leap(year):
  if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
  return False

year = int(input())
print(is_year_leap(year))

#5.
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

N = int(input("Введите число: "))
res = is_prime(N)

if res:
    print(f"{N} - простое число.")
else:
    print(f"{N} - не простое число.")

#6.
a = int(input())
b = int(input())
c = [(-138 / 2) ** 1.3]
d = [abs((-69 / 28 ** 5.1) * 4)]
if a * 3.6 > b or (b in c and b in d):
    temp = a
    a = b
    b = temp

print("a =", a)
print("b =", b)

#7.
numbers = []
even_count = 0
negative_count = 0
range_count = 0

for i in range(5):
    number = int(input("Введите число: "))
    numbers.append(number)
    if number % 2 == 0:
        even_count += 1
    elif number < 0:
        negative_count += 1
    elif -256 <= number <= 1024:
        range_count += 1

print("Все числа уникальны:", numbers.count(numbers[0]) == 1 and len(numbers) == len(set(numbers)))
print("Количество четных:", even_count)
print("Количество отрицательных:", negative_count)
print("Количество чисел в диапазоне [-256 ; 1024]:", range_count)

#8.
a = int(input())
b = int(input())
c = int(input())
res = ((a ** 2 + b ** 3) // (c + 3)) // 4
print(res)
if res % 2 == 0:
    print('Число чётное')
else:
    print('Число нечётное')